services:
  - type: web
    name: sistema-mantenimiento-ucv
    runtime: docker
    plan: free
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sistemamantenimiento-ucvvirtual-df9a.a.aivencloud.com
      - key: DB_PORT
        value: "16502"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_8P-_xxkOOC5pvRdeXkY
      - key: MYSQL_ATTR_SSL_CA
        value: ""
      - key: DB_SSL_MODE
        value: REQUIRED
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        value: base64:uR8vG1kXj3R+/saMwPlZmTXv6eFerPgs+A+J0K/zhOw=
      - key: APP_URL
        value: https://sistema-mantenimiento-ucv-ertf.onrender.com
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file